#! /usr/bin/env python
# encoding: utf-8

source = ['src/test_symbol_id.cpp',
          'src/test_symbol_id_layers.cpp',
          'src/test_file_xyz.cpp',
          'src/test_rlnc_full_vector_codes.cpp',
          'src/test_symbol_storage_xyz.cpp',
          'src/test_coefficient_storage_xyz.cpp',
          'src/test_coefficient_generator.cpp',
          'src/test_carousel_codes.cpp',
          'src/test_object_xyz.cpp',
          'src/test_random_annex.cpp',
          'src/test_rs_vandermonde_matrix.cpp']
          #'src/test_rs_reed_solomon_codes.cpp']

bld.program(
    features = 'cxx test',
    #source   = ['kodo_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    source   = ['kodo_tests.cpp'] + source,
    target   = 'kodo_tests',
    use = ['kodo_includes', 'fifi_includes', 'sak_includes',
           'gtest', 'boost_includes', 'boost_system', 'boost_filesystem'])
