#! /usr/bin/env python
# encoding: utf-8


bld.program(
    features = 'cxx',
    source   = ['kodo_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target   = 'kodo_tests',
    cxxflags = bld.toolchain_cxx_flags(),
    use = ['kodo_includes', 'fifi_includes', 'sak_includes',
           'gtest', 'boost_includes'])
