#! /usr/bin/env python
# encoding: utf-8

bld.program(features = 'cxx',
            source   = 'use_debug_layers.cpp',
            target   = 'use_debug_layers',
            use      = ['kodo_includes', 'boost_includes',
                        'fifi_includes', 'sak_includes'])

